### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "f89a89bc06734a0f70b04fb3dedc0507eb7ab910";
          sha256 = "190rhp1xn8szsqf8bvwa30avm7nxrf2f5yjkl6wc6xlql2l97g3h";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
      satysfi-external = 
      rec {
        fetch = 
        {
          owner = "gfngfn";
          repo = "satysfi-external-repo";
          rev = "dae3996a85f2c2bf2a1ae58594d0e1cacea08cf7";
          sha256 = "19fyjh99jm5ij8qr9vpncwrg8jxys767p17sl8fd6yas0gkdl7gc";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.13.1";
  selection = 
  {
    base = 
    {
      pname = "base";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/v0.14.3.tar.gz";
        sha256 = "0nmydvlbw124c0qz80fx1rpggpr00ylp2zpnyn26qf1a0pfw0kg3";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.14.3";
        hash = "sha256:1v61rsyfwkpla41ga6hsagzjihmn1lg5whg2gwb01w9xhdy95qd2";
      };
    };
    base-bigarray = 
    {
      pname = "base-bigarray";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bigarray/base-bigarray.base";
        hash = "sha256:1hgfwxh4vdv21m2a4g506y27pcv912v67qi4svrn53rgc43ckv6b";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base_bigstring = 
    {
      pname = "base_bigstring";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/base_bigstring-v0.14.0.tar.gz";
        sha256 = "1fhldk58w56ixkin763kpic512xvkkf9b4mrnjfsbm8in75kzndq";
      };
      opamInputs = 
      {
        inherit (selection) ppx_jane ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base_bigstring/base_bigstring.v0.14.0";
        hash = "sha256:0yn51npq4fwi9nllfhq2r3kkb17pg3igvvjgblac1g3v0nmhj6c4";
      };
    };
    base_quickcheck = 
    {
      pname = "base_quickcheck";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base_quickcheck/archive/v0.14.1.tar.gz";
        sha256 = "0n5h0ysn593awvz4crkvzf5r800hd1c55bx9mm9vbqs906zii6mn";
      };
      opamInputs = 
      {
        inherit (selection) splittable_random ppxlib ppx_sexp_value
        ppx_sexp_message ppx_let ppx_fields_conv ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base_quickcheck/base_quickcheck.v0.14.1";
        hash = "sha256:0lxxagkyg1jh0x7bbps1972bid51a82m1h2x3nyz342dnsy4k6h1";
      };
    };
    batteries = 
    {
      pname = "batteries";
      version = "3.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-batteries-team/batteries-included/archive/refs/tags/v3.5.1.tar.gz";
        sha256 = "0cljqgljjxskdmc6zds7dyd3jqdks3k3bgq641f8s2fjmw90yqqs";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml num;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/batteries/batteries.3.5.1";
        hash = "sha256:18ykh8m4ra2ghz9zy4nhij7y6i7c7hcsqgqmsc2nfjclqq8mhqil";
      };
    };
    bin_prot = 
    {
      pname = "bin_prot";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/bin_prot-v0.14.0.tar.gz";
        sha256 = "1f1ng6cixi3ci0nb765yfzqk9b3s752hy1i3702kh59gni1psycp";
      };
      opamInputs = 
      {
        inherit (selection) ppx_variants_conv ppx_sexp_conv ppx_optcomp
        ppx_fields_conv ppx_custom_printf ppx_compare ocaml dune
        base;
        mirage-xen-ocaml = selection.mirage-xen-ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bin_prot/bin_prot.v0.14.0";
        hash = "sha256:17ylwhh1kv9klavfag20n4g3175i7nmljbdj12z9yiqm4da3r4rk";
      };
    };
    biniou = 
    {
      pname = "biniou";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/biniou/releases/download/1.2.1/biniou-1.2.1.tbz";
        sha256 = "0da3m0g0dhl02jfynrbysjh070xk2z6rxcx34xnqx6ljn5l6qm1m";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/biniou/biniou.1.2.1";
        hash = "sha256:1m9s9v4zr7022k6d50482qq7w41fdqp58nkpfhcp8574hg65kh69";
      };
    };
    camlimages = 
    {
      pname = "camlimages";
      version = "5.0.4-1";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.com/camlspotter/camlimages/-/archive/5.0.4/camlimages-5.0.4.tar.bz2";
        sha256 = "0r984hh4mz7p6ac1b1558wz229j973gxm46lb7wcjj6kqfyni6hw";
      };
      opamInputs = 
      {
        inherit (selection) stdio ocamlfind ocaml dune-configurator dune cppo
        base;
        lablgtk = selection.lablgtk or null;
        graphics = selection.graphics or null;
        conf-libpng = selection.conf-libpng or null;
        conf-libjpeg = selection.conf-libjpeg or null;
        conf-libgif = selection.conf-libgif or null;
        conf-ghostscript = selection.conf-ghostscript or null;
        conf-freetype = selection.conf-freetype or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/camlimages/camlimages.5.0.4-1";
        hash = "sha256:1j2k6494q1b7dda9lwjbrcq3fn771szdccdrrfm2m2p3d8b25i3k";
      };
    };
    camlpdf = 
    {
      pname = "camlpdf";
      version = "2.3.1-satysfi";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gfngfn/camlpdf/archive/v2.3.1+satysfi.tar.gz";
        sha256 = "1ffgk361kxyyhahah40hvq9y0dxxipxsg3d28d5ax3a3s2i603j4";
      };
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.satysfi-external.src) 
      {
        package = "packages/camlpdf/camlpdf.2.3.1+satysfi";
        hash = "sha256:1xqpgl2myabj95cbbrp4l0awh5gk4lpgkxm5x96fimdv22iharq9";
      };
    };
    core_kernel = 
    {
      pname = "core_kernel";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/core_kernel/archive/v0.14.2.tar.gz";
        sha256 = "0jyf08i9wzg3yf32f158i6n9gm751bk8zj7xqx79jnnkchwkbxb6";
      };
      opamInputs = 
      {
        inherit (selection) variantslib typerep time_now stdio
        splittable_random sexplib ppx_sexp_message ppx_sexp_conv ppx_optcomp
        ppx_jane ppx_inline_test ppx_hash ppx_base ppx_assert ocaml
        jst-config jane-street-headers fieldslib dune bin_prot
        base_quickcheck base_bigstring base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/core_kernel/core_kernel.v0.14.2";
        hash = "sha256:09c7k6m1vm8jhqfivn8w663v362qwjf6cb5xlzijd0sjgh1dwai5";
      };
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz";
        sha256 = "0lxy4xkkkwgs1cj6d9lyzsqi9f6fc9r6cir5imi7yjqrpd86s1by";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.8";
        hash = "sha256:0pzd8irqkkkpfgw8nq9d21z9rj5m3qlzixyb7ybfy4b1fwh3n8bp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
        sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.1";
        hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "3.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.1.1/fiber-3.1.1.tbz";
        sha256 = "0q3bbarnkxglypw2w4rccs9fn093dgn0jdc7qx08i68vmda48j02";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.3.1.1";
        hash = "sha256:1ik4iy7xfwyk7f6ywqza6ckwk736f4mgp6q18jnazcrnk56md5wx";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "3.1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/3.1.1/fiber-3.1.1.tbz";
        sha256 = "0q3bbarnkxglypw2w4rccs9fn093dgn0jdc7qx08i68vmda48j02";
      };
      opamInputs = {
                     inherit (selection) ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.3.1.1";
        hash = "sha256:1hbj4q7kdnjd5ankmm8k2yj5psn9nnf445ajb8yb3adfxiwjhzvm";
      };
    };
    easy-format = 
    {
      pname = "easy-format";
      version = "1.3.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mjambon/easy-format/releases/download/1.3.3/easy-format-1.3.3.tbz";
        sha256 = "05n4mm1yz33h9gw811ivjw7x4m26lpmf7kns9lza4v6227lwmz7a";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/easy-format/easy-format.1.3.3";
        hash = "sha256:0w8bsfr039gbpz0abdarfy4bnz224zr134abw5i6n4lppqd83csf";
      };
    };
    fieldslib = 
    {
      pname = "fieldslib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/fieldslib-v0.14.0.tar.gz";
        sha256 = "10n5y376fb5jgqk9h8vq158rm1b36h9lzh6p11q33h6xgvb1v6n3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fieldslib/fieldslib.v0.14.0";
        hash = "sha256:1gsrbs4x45k4bp1zih9c6db3axhaiy91knac6bk6hpgv9sjalicm";
      };
    };
    jane-street-headers = 
    {
      pname = "jane-street-headers";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/jane-street-headers-v0.14.0.tar.gz";
        sha256 = "028yxb4h3iy025iy89v8653m5brh7flrjshghs4x99pd690pmfs7";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jane-street-headers/jane-street-headers.v0.14.0";
        hash = "sha256:1w6zjjmyszk9pax139rkxb3vx0w23w0pfd46bddfyfkxq2rbwsvf";
      };
    };
    jst-config = 
    {
      pname = "jst-config";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/jst-config/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "0wdjs0lvc5wbggh27cf490jarfibrrb5xxsrigg41m32kjkbijm4";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppx_assert ocaml dune-configurator dune
        base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jst-config/jst-config.v0.14.1";
        hash = "sha256:0myym84b9yx4vqa0ml0zf3cx6rms3g5dv704vhf5bpr7jnqz0qcb";
      };
    };
    menhir = 
    {
      pname = "menhir";
      version = "20220210";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20220210/archive.tar.gz";
        sha256 = "0dapvzw55y9ggadh7ahya22s6r972c2n2nx6jsw5437ryldfi92p";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20220210";
        hash = "sha256:0v2w4jslcpd39ra755fg3731q2l565h78cg0rly6rw61ja7d1808";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20220210";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20220210/archive.tar.gz";
        sha256 = "0dapvzw55y9ggadh7ahya22s6r972c2n2nx6jsw5437ryldfi92p";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20220210";
        hash = "sha256:0nl416snigjxz4w4fkvgfss6g6viqnixzcjysww7rpj7fs39rpqq";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20220210";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20220210/archive.tar.gz";
        sha256 = "0dapvzw55y9ggadh7ahya22s6r972c2n2nx6jsw5437ryldfi92p";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20220210";
        hash = "sha256:182rqysmqw0z0zfwagq8wcbl42xrz1rnn09r9c283m2n7iv0n3a9";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
        sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
      };
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.4";
        hash = "sha256:0q683bfsbw9k3vzzxpnjv2sgjdas97aybqz19acnm14ihnalbzm2";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.13.1";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.13.1";
        hash = "sha256:12aajj2hc636jr6wbv4vba8pmjdndbcvnw7q35gj4agxmrjspziw";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.13.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.13.1.tar.gz";
        sha256 = "1i7ad8lh5l74wb3yzmhlv529wc75a5sjybzkad7wdl8zrj47jk0r";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.13.1";
        hash = "sha256:069i5vsndd9lsvdm5wk898nfnc85ww7459nibjg6881ww43w8ck1";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "2";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.2";
        hash = "sha256:0h0hgqq9mbywvqygppfdc50gf9ss8a97l4dgsv3hszmzh6gglgrg";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.14.1.tar.gz";
        sha256 = "0ml2y3dqhhbwlf94l3jgz6gfhhfp41qaf1sjm8p8c37q1vzpj4jf";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.1";
        hash = "sha256:04ws6wbbsv56r4b6f29514inn77d91gb6sa8z62bxkswk1s1r1fn";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.3";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.3.tar.gz";
        sha256 = "0hfcwamcvinmww59b5i4yxbf0kxyzkp5qv3d1c7ybn9q52vgq463";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.3";
        hash = "sha256:1wq1lkw3rpgilprlakznsxxf60mcidn3fzi3vjrgjdrnnp9hvh19";
      };
    };
    octavius = 
    {
      pname = "octavius";
      version = "1.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-doc/octavius/archive/v1.2.2.tar.gz";
        sha256 = "1bg0fcm7haqxvx5wx2cci0mbbq0gf1vw9fa4kkd6jsriw1611jga";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/octavius/octavius.1.2.2";
        hash = "sha256:0bagilkanfjyi56hrk9dw43xs6zry9p8n3l55r3d58v5hz2xsbwl";
      };
    };
    omd = 
    {
      pname = "omd";
      version = "1.3.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/Chris00/omd/releases/download/1.3.1/omd-1.3.1.tar.gz";
        sha256 = "1sgdgzpx96br7npj8mh91cli5mqmzsjpngwm7x4212n3k1d0ivwa";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml base-bytes
        base-bigarray;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/omd/omd.1.3.1";
        hash = "sha256:09fzyagdfcj1b2bwj5hacbda9lldicd0a59sac5j5nls8x8rsgcc";
      };
    };
    otfm = 
    {
      pname = "otfm";
      version = "0.3.7-satysfi";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gfngfn/otfm/archive/v0.3.7+satysfi.tar.gz";
        sha256 = "17vcm0kchz4qkhaixsnsfp6gj9wlia9nq93cra9inf37m934lfza";
      };
      opamInputs = 
      {
        inherit (selection) uutf uchar topkg result ocamlfind ocamlbuild
        ocaml;
      };
      opamSrc = repoPath (repos.satysfi-external.src) 
      {
        package = "packages/otfm/otfm.0.3.7+satysfi";
        hash = "sha256:1ghkp3njb819izl20cczakgyg5r63h6r8rn3h5ycdq344yi5ihcm";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/parsexp/archive/refs/tags/v0.14.2.tar.gz";
        sha256 = "0c7jl6sqfawqpvbhci8vyyhgvcyd3lw5lj3jcf5f1p6w1177xqgn";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.14.2";
        hash = "sha256:1fqnxdr1pgxmada77hkhyyr7yybpv2f810shnhvhkpw15h58azx1";
      };
    };
    ppx_assert = 
    {
      pname = "ppx_assert";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_assert-v0.14.0.tar.gz";
        sha256 = "1l2rr4jz2q5b35ryn2z146z7m9v6k8krp5gpn8ilib66mnz5zx15";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ppx_compare
        ppx_cold ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_assert/ppx_assert.v0.14.0";
        hash = "sha256:1ry1bqssjw5lc7h0x2cc7f8rmz807j5l7029lxd4i12vgq91x5km";
      };
    };
    ppx_base = 
    {
      pname = "ppx_base";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_base-v0.14.0.tar.gz";
        sha256 = "0b7a3fmi90jk8paz0g36yzaq670fbnrbi1j8r5ibh9wbcfli7ji6";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_js_style ppx_hash
        ppx_enumerate ppx_compare ppx_cold ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_base/ppx_base.v0.14.0";
        hash = "sha256:1n66x8xl2n0qbq1g0b1l3nsdqlb3czj5w509riwqdgz11fyrzi25";
      };
    };
    ppx_bench = 
    {
      pname = "ppx_bench";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_bench/archive/v0.14.1.tar.gz";
        sha256 = "1jr3cf4zsk894x64c8ir9ap9l412q35b2605pr7flrlxbm4vkf3f";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_inline_test ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_bench/ppx_bench.v0.14.1";
        hash = "sha256:0r17lcfhxd14ihbbhqjqjmx26ig4xf62dmc2pblg7flzcf4k64dp";
      };
    };
    ppx_bin_prot = 
    {
      pname = "ppx_bin_prot";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_bin_prot-v0.14.0.tar.gz";
        sha256 = "0wa2jmvm2k88b37pbcafy1mdf5iaip0yxg5dw774sbh28nm08m2s";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_here ocaml dune bin_prot base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_bin_prot/ppx_bin_prot.v0.14.0";
        hash = "sha256:0rsbhajm4927f1798baalwf3f7f5vs8jy27bxd6rhhybnvqjxyj9";
      };
    };
    ppx_cold = 
    {
      pname = "ppx_cold";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_cold-v0.14.0.tar.gz";
        sha256 = "1madfzhpir9amnxmg530n70vll0jrl59vyp71miji73i6b9sy6n2";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cold/ppx_cold.v0.14.0";
        hash = "sha256:0g566vskiblrxr246c3s26rlzxciln518fr4f6d8lid63qgrgnfm";
      };
    };
    ppx_compare = 
    {
      pname = "ppx_compare";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_compare-v0.14.0.tar.gz";
        sha256 = "0mqxa2s194nif7x4fjn1p5gd9i3bakr8nv27gf8x1g5nmi8q9pmp";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_compare/ppx_compare.v0.14.0";
        hash = "sha256:1ndfsgazb7yg5q3aqzcrnr914sf615bsh4z4q202bdvpf0fqj31k";
      };
    };
    ppx_custom_printf = 
    {
      pname = "ppx_custom_printf";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_custom_printf/archive/v0.14.1.tar.gz";
        sha256 = "0kzbckbvhfn3s9an1hq01qd5iac7wgirw182ablpqxc6r3dmijrl";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_custom_printf/ppx_custom_printf.v0.14.1";
        hash = "sha256:1karjqaa17ai6v4y7wb2zwfpscyirmb4ixdr3lw6i83icklsgmdw";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:1hj1ina0n7pgz16mrvijczapw75pd0hif0i18dpw7d1fyg2qr8py";
      };
    };
    ppx_deriving = 
    {
      pname = "ppx_deriving";
      version = "5.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_deriving/releases/download/v5.2.1/ppx_deriving-v5.2.1.tbz";
        sha256 = "11h75dsbv3rs03pl67hdd3lbim7wjzh257ij9c75fcknbfr5ysz9";
      };
      opamInputs = 
      {
        inherit (selection) result ppxlib ppx_derivers ocamlfind ocaml dune
        cppo;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_deriving/ppx_deriving.5.2.1";
        hash = "sha256:0n4j9a5qh5fzxc68shhkhwqfajz49rjb8ryp9lx8ykl1zxddf89k";
      };
    };
    ppx_enumerate = 
    {
      pname = "ppx_enumerate";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_enumerate-v0.14.0.tar.gz";
        sha256 = "1ij6sffgqhnjwnj9brhrrw1c6xgxlh0s6r17x1qkgnyrc73gfsz8";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_enumerate/ppx_enumerate.v0.14.0";
        hash = "sha256:0lgnrpq1vmb44367y7mdr7jw1yqmy08fi6phgq8pch3a47fdk2rm";
      };
    };
    ppx_expect = 
    {
      pname = "ppx_expect";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_expect/archive/v0.14.2.tar.gz";
        sha256 = "1gcjlya6knnsrl60sd3vlgp7arj39xm5fjjfk5sick4z66agm2n5";
      };
      opamInputs = 
      {
        inherit (selection) stdio re ppxlib ppx_inline_test ppx_here ocaml
        dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_expect/ppx_expect.v0.14.2";
        hash = "sha256:14hnawvs9fc87kghg00zj0p1p21f22gdy1767l2nwb4ihl3h133b";
      };
    };
    ppx_fields_conv = 
    {
      pname = "ppx_fields_conv";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_fields_conv/archive/v0.14.2.tar.gz";
        sha256 = "0r7d51j54r1za6bwqsmhmhhfab8n10zyk5zznhkm91f20dx9ddip";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml fieldslib dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_fields_conv/ppx_fields_conv.v0.14.2";
        hash = "sha256:0332mrn1xk3423rm4hk5lif9igrj3339xyfd6464wcbkpakivfba";
      };
    };
    ppx_fixed_literal = 
    {
      pname = "ppx_fixed_literal";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_fixed_literal-v0.14.0.tar.gz";
        sha256 = "0w0a06143mhmczbpr0lfb66r6im7075gck4p0idbcari63sximqj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_fixed_literal/ppx_fixed_literal.v0.14.0";
        hash = "sha256:13wng3z0x3fx6l4vym8rddc0yniplim94gn5x8bcfkjd2yhxd88s";
      };
    };
    ppx_hash = 
    {
      pname = "ppx_hash";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_hash-v0.14.0.tar.gz";
        sha256 = "0x4wgdvhgd8a49bzari52jpkykxpv6ncgp5ncda3xgg0a9r49s8n";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_compare ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_hash/ppx_hash.v0.14.0";
        hash = "sha256:0zcnsd0724w6kpx4w1i3nbfrvffhnqjn3rinddgqjndx5pvghrlc";
      };
    };
    ppx_here = 
    {
      pname = "ppx_here";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_here-v0.14.0.tar.gz";
        sha256 = "0b444djy68v6ji0ypwv5l02pkl151qzrgg96lyhl8dxfrzvj1zkj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_here/ppx_here.v0.14.0";
        hash = "sha256:0f7p619ymqm27iclcx3cbyyn1k0mccw9vsa0l88m1jk3kjgjbmzz";
      };
    };
    ppx_inline_test = 
    {
      pname = "ppx_inline_test";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_inline_test/archive/v0.14.1.tar.gz";
        sha256 = "0qzvm8rg07annl8zpqlhzx1z8ahrrf02r1brd43ykqas5sww3rfp";
      };
      opamInputs = 
      {
        inherit (selection) time_now ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_inline_test/ppx_inline_test.v0.14.1";
        hash = "sha256:1vwg8bgw093ia075n7vh0kl82sjd5r9yk27s45ljzz9cmfqrr4sa";
      };
    };
    ppx_jane = 
    {
      pname = "ppx_jane";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_jane-v0.14.0.tar.gz";
        sha256 = "18js98xdqf8d54sjn1gccjkwbv2p56qy7bhvjgk94pr3fipfz0v7";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_variants_conv ppx_typerep_conv
        ppx_string ppx_stable ppx_sexp_value ppx_sexp_message ppx_pipebang
        ppx_optional ppx_optcomp ppx_module_timer ppx_let ppx_inline_test
        ppx_here ppx_fixed_literal ppx_fields_conv ppx_expect
        ppx_custom_printf ppx_bin_prot ppx_bench ppx_base ppx_assert ocaml
        dune base_quickcheck;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_jane/ppx_jane.v0.14.0";
        hash = "sha256:1jqzfdg3rbb96mgw0cpbsmr1y06whhqys6a4rkfdih6z4n5cm4ns";
      };
    };
    ppx_js_style = 
    {
      pname = "ppx_js_style";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_js_style/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "1nq4rj659f34dc28pj7ir2szqbpky4nzs9qfw0am6sf36jwispiw";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib octavius ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_js_style/ppx_js_style.v0.14.1";
        hash = "sha256:05bc07ghvfd4d85inf1qvpqxphvcg7mgf8fn9ycib6fdmxdkkamq";
      };
    };
    ppx_let = 
    {
      pname = "ppx_let";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_let-v0.14.0.tar.gz";
        sha256 = "1qcrnd86pbr1di5m6z4ps4p15qawwa02jxwz3xfd82hdbjmdwf1s";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_let/ppx_let.v0.14.0";
        hash = "sha256:1n3ayvvmiwmv5jnyjl8nr510dblijwx9g2r39hl5xxgr57d4c7f7";
      };
    };
    ppx_module_timer = 
    {
      pname = "ppx_module_timer";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_module_timer-v0.14.0.tar.gz";
        sha256 = "04a7vzk4s3jn6wj94q0hn8kd9vxlzkpcq5ifpvz3bdfgmypjks5z";
      };
      opamInputs = 
      {
        inherit (selection) time_now stdio ppxlib ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_module_timer/ppx_module_timer.v0.14.0";
        hash = "sha256:18q8zyppvl9wskx5flhcfmkznzihfs3kk3c38n0kdh1ngg6c1prr";
      };
    };
    ppx_optcomp = 
    {
      pname = "ppx_optcomp";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_optcomp/archive/v0.14.3.tar.gz";
        sha256 = "0bxzh0pm3zdiadrd37jjzp7zm2qn28mx25ahk0shgfb73vya809n";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optcomp/ppx_optcomp.v0.14.3";
        hash = "sha256:0xh7m3hsm7vrhzmd86n3irhydp9lyr23ax9mg1khq2jhcbyqqvy0";
      };
    };
    ppx_optional = 
    {
      pname = "ppx_optional";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_optional-v0.14.0.tar.gz";
        sha256 = "1hh6ivlp1qpvyn8l0vhrahkkcp3scf7km254sgplprmk10wnyidz";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_optional/ppx_optional.v0.14.0";
        hash = "sha256:0jg35ql4vwzh27hv2vn52hilfb2cpdl91wiaj0r6nh9s6iwy8dzf";
      };
    };
    ppx_pipebang = 
    {
      pname = "ppx_pipebang";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_pipebang-v0.14.0.tar.gz";
        sha256 = "19afbbvy72i1347prvkpy3ms75xnk7kl2hn83h40p6yh27100hky";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_pipebang/ppx_pipebang.v0.14.0";
        hash = "sha256:1rklw915zv3apij5icp19337aza8di19sp86qp0w6lwimmdvx7dn";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.3.tar.gz";
        sha256 = "0fbnkhsd6yphc49pa21nlmbik99n7qkaz8l9paq96v012ipg9h9g";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.3";
        hash = "sha256:0f1bxwrzykh72b7dzjqn4bydcmfli6bnd19wmwqw2z6n0y9crz41";
      };
    };
    ppx_sexp_message = 
    {
      pname = "ppx_sexp_message";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_message/archive/v0.14.1.tar.gz";
        sha256 = "06d1cx8nh6chgx09lqjgsagc02lfsvv18fydrviqjvydx52m2qjf";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_message/ppx_sexp_message.v0.14.1";
        hash = "sha256:0djv8npvc7lx1d20f3ln3s3hffh729fpyyj156fpylkqnr9lcfv7";
      };
    };
    ppx_sexp_value = 
    {
      pname = "ppx_sexp_value";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/ppx_sexp_value-v0.14.0.tar.gz";
        sha256 = "0yc6i1yx9mb8pwjkswy09aqg5kz1hgrpjyniq2v6whfjvxl1qrkj";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ppx_sexp_conv ppx_here ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_value/ppx_sexp_value.v0.14.0";
        hash = "sha256:0wqj7nr9nvyss3qjf5jcbijjqkrah2ib8ypfp4hxw00vmyfvyrps";
      };
    };
    ppx_stable = 
    {
      pname = "ppx_stable";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_stable/archive/v0.14.1.tar.gz";
        sha256 = "1dw8ilrvi5lssxnbflnzskmyi3k93ij2kbyz49y93agv0b8dsq01";
      };
      opamInputs = 
      {
        inherit (selection) ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_stable/ppx_stable.v0.14.1";
        hash = "sha256:1b2kvif9jc2wj99ciaz6876myn05qbk3a7gn40msnpmd9prgg1lc";
      };
    };
    ppx_string = 
    {
      pname = "ppx_string";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_string/archive/v0.14.1.tar.gz";
        sha256 = "1a8f7bplbxvwm4lh0m57j89jkwkxfm9r5ndcvvlj5v6py8pv69wj";
      };
      opamInputs = 
      {
        inherit (selection) stdio ppxlib ppx_base ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_string/ppx_string.v0.14.1";
        hash = "sha256:0adczy40rfpif3jwz2vrhf8kphzilvgffws2si9ypzs264ipjvg8";
      };
    };
    ppx_typerep_conv = 
    {
      pname = "ppx_typerep_conv";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_typerep_conv/archive/v0.14.2.tar.gz";
        sha256 = "1g1sb3prscpa7jwnk08f50idcgyiiv0b9amkl0kymj5cghkdqw0n";
      };
      opamInputs = 
      {
        inherit (selection) typerep ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_typerep_conv/ppx_typerep_conv.v0.14.2";
        hash = "sha256:13fsnz1ndp973s265alzn2l8r1s5bwyica864xgl247yp77f8yy2";
      };
    };
    ppx_variants_conv = 
    {
      pname = "ppx_variants_conv";
      version = "v0.14.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_variants_conv/archive/v0.14.2.tar.gz";
        sha256 = "06d63vi2ijzqa3wqnywwqywldq72karss39zi47d544y10rq4rid";
      };
      opamInputs = 
      {
        inherit (selection) variantslib ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_variants_conv/ppx_variants_conv.v0.14.2";
        hash = "sha256:0x7xyzzdp9gpx3j32nkh8n1baw8831ppa40c5s4lb4f5gpzjg9m9";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.25.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.25.0/ppxlib-0.25.0.tbz";
        sha256 = "1m8bhw9adzdyh5zfddw6r5qvw03nlq2zfm6jg32mv10mfw71abrd";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.25.0";
        hash = "sha256:0l9rjdc91kklyw39dl5ff6gxvlgd1kry2fgm89vjm83i437lwa2c";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.10.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.10.4/re-1.10.4.tbz";
        sha256 = "0z3lracww84cswj0a4s28x987sk28c7h2j87hb3iv6xa011kxsw3";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.10.4";
        hash = "sha256:00918wlxkkbj8dwpiwpyyvc8falk4ddrf0pxn5v2kahc2jl251vg";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    satysfi = 
    {
      pname = "satysfi";
      version = "0.0.7";
      src = self.directSrc "satysfi";
      opamInputs = 
      {
        inherit (selection) yojson-with-position uutf re ppx_deriving otfm
        omd ocamlfind ocaml menhir dune cppo core_kernel camlpdf camlimages
        batteries;
      };
      opamSrc = "satysfi.opam";
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib-v0.14.0.tar.gz";
        sha256 = "12rlnc6fcrjfdn3gs2agi418sj54ighhs6dfll37zcv7mgywblm2";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.14.0";
        hash = "sha256:1nlzjkx60d4z09b15nq35ivzl6akk3svq7nl4vv5swhsmj8gvpl4";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.14.0";
        hash = "sha256:0k9vkjbiibja48c0yayal7xwyik3h3c3v4dwd3j7jbmras63ig2c";
      };
    };
    splittable_random = 
    {
      pname = "splittable_random";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/splittable_random-v0.14.0.tar.gz";
        sha256 = "185rpmdnrzs80br138pnjbx9hfp1046zvj1ap0brq1sxdwzak6lf";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_message ppx_inline_test ppx_bench
        ppx_assert ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/splittable_random/splittable_random.v0.14.0";
        hash = "sha256:14s1ka5p5af599ira53kygzny65ls49vkxw3xk9ia5xavp7gv4bp";
      };
    };
    stdio = 
    {
      pname = "stdio";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/stdio-v0.14.0.tar.gz";
        sha256 = "1hj5hraprqy2i90a690l11yjszvb99j818q3d684ryx6p2lddk0l";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdio/stdio.v0.14.0";
        hash = "sha256:19hlf6bgx1avq4ifwji2rj2f2j26v3nf8ywjnwh2m3dpvfqc4pvk";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:1hwyzzcx7clz4p58fj3n6frq2srbxdmhmxxd6n6mpw9gj2vs6yiw";
      };
    };
    time_now = 
    {
      pname = "time_now";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/time_now-v0.14.0.tar.gz";
        sha256 = "0hkn2jw4dz5gflnsblskl5wp6z7zbrahwjmaxmsskfviwjg82cqh";
      };
      opamInputs = 
      {
        inherit (selection) ppx_optcomp ppx_base ocaml jst-config
        jane-street-headers dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/time_now/time_now.v0.14.0";
        hash = "sha256:1s8bqbks0cjw4x68nn5xlkykn3bcqh2rmrx6hgs53dalkiqv7ry0";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.5.tbz";
        sha256 = "1iyinmcfqpprk7k4cc51nqgypayprbj4larwcfqw86k5dri84825";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.5";
        hash = "sha256:04vg4zic7f6zk44vkvqw2fcr562hl7d0gklv3vgphk4n3bnqbcyy";
      };
    };
    typerep = 
    {
      pname = "typerep";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/typerep-v0.14.0.tar.gz";
        sha256 = "0rmp5jsjg6sgn5yx0pcvch0phs7nak2fg1d48g5sjcyyyj8n1279";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/typerep/typerep.v0.14.0";
        hash = "sha256:1hhgz8nrarcmbrnknah05wlz3yf1sq4j4mjgjajmbjnls26dkyfa";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:028vff7rkmhyyn3xr5flfkc3ihz0axirbg538an8wbsmc4y1gv02";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz";
        sha256 = "0s05r8ggp1g97zq4rnvbxzj22pv8ld0k5wsdw662jw0y7mhsawl7";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.3";
        hash = "sha256:1x57h3bc68rsm2kd18wjbkfjk67shak6jgplp7paw97faqgmgx3x";
      };
    };
    variantslib = 
    {
      pname = "variantslib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/variantslib-v0.14.0.tar.gz";
        sha256 = "11zp27gh282dx9ifbhcp6i7fkc97fvk8amaj58mf1g1hwklc0lm3";
      };
      opamInputs = {
                     inherit (selection) ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/variantslib/variantslib.v0.14.0";
        hash = "sha256:1g0z5w2wgsj59vrz7mdzjxdg0vxhck0q8yvzhvag77xzw85r5kjs";
      };
    };
    yojson-with-position = 
    {
      pname = "yojson-with-position";
      version = "1.4.2-satysfi";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/gfngfn/yojson-with-position/archive/v1.4.2+satysfi.tar.gz";
        sha256 = "12mxck0n7sj99f93l9v7gk3c6ncij0scbyzl80wfch9319yv7dck";
      };
      opamInputs = 
      {
        inherit (selection) ocaml easy-format dune cppo biniou;
      };
      opamSrc = repoPath (repos.satysfi-external.src) 
      {
        package = "packages/yojson-with-position/yojson-with-position.1.4.2+satysfi";
        hash = "sha256:0fr367p0ayx2dil1h2c2rajkqssl793wblvfycs7ing48m0wqnk4";
      };
    };
  };
}

